apiVersion: v1
kind: Service
metadata:
 name: helloworld
spec:
 type: NodePort
 selector:
   app: helloworld
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: helloworld
